### ISSUE TITLE
LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)

### ISSUE THREAD

**Issue by catalin88** [vinsol-spree-contrib/spree-admin-insights#28] opened 2017-03-13 15:18 UTC
I get this error while trying to install the 3-1-stable branch:

`/usr/local/rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in require': LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)`

Any ideas ?

**Comment by AnuragBhardwaj1** [comment] 2017-04-06 08:29
@catalin88 
I think the error here is due to different adapter names for sqlite.
Sequel -> uses 'sqlite' as :adapter
sqlite gem -> uses 'sqlite3' as :adapter

as a solution we can modify params while connecting with Sequel in after_initialize.

**Comment by dsawa** [comment] 2017-04-06 21:04
Nice, looking forward to see your fix merged.

**Comment by AnuragBhardwaj1** [comment] 2017-04-11 12:09
@catalin88 
Is this PR solves your issue ?

**Comment by dsawa** [comment] 2017-04-25 10:52
@AnuragBhardwaj1 
While @catalin88 is missing, I can confirm that this fixed same issue for me.

**Comment by AnuragBhardwaj1** [comment] 2017-04-25 12:25
Thanks @catalin88 for the feedback.
Closing issue.

**Closed by AnuragBhardwaj1** 2017-04-25 12:25 UTC
